# This workflow tests and lints the Python code of the plugin. If a release is created, it will upload the package to https://pypi.org.

# For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ninja-bear-language-typescript pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ '*' ]
  release:
    types:
      - 'created'

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Github environment
      uses: actions/checkout@v2
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Prepare Python
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install ruff coverage[toml] ninja-bear
    - name: Run tests
      shell: bash
      run: |
        python3 -m unittest discover tests || exit -1
    - name: Check coverage
      shell: bash
      run: |
        python3 -m coverage run -m unittest || exit -1
        python3 -m coverage report || exit -1
    - name: Lint
      run: |
        python3 -m ruff check . || exit -1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test_and_lint
    if: ${{ github.event_name == 'release' }}  # Build release only on release event.
    steps:
    - name: Prepare Github environment
      uses: actions/checkout@v2
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build
    - name: Build package
      run: |
        python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
